"""Report export: render saved benchmark reports as HTML or CSV."""
import csv
import html
import io
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


def _get(report: Dict[str, Any], *path: str, default: Any = None) -> Any:
    node: Any = report
    for key in path:
        if not isinstance(node, dict) or key not in node:
            return default
        node = node[key]
    return node


def _fmt(value: Optional[float], suffix: str = "", digits: int = 2) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.{digits}f}{suffix}"
    return f"{value}{suffix}"


GRADE_COLORS = {
    "A": "#22c55e",
    "B": "#84cc16",
    "C": "#f59e0b",
    "D": "#ef4444",
    "F": "#dc2626",
}


def generate_html(report: Dict[str, Any]) -> str:
    """Render a benchmark report as a self-contained HTML page."""
    model = _get(report, "model", "name", default="Unknown model")
    grade = _get(report, "comparator", "grade", default="?")
    grade_color = GRADE_COLORS.get(grade, "#6b7280")
    tps = _get(report, "metrics", "tokens_per_sec")
    baseline = _get(report, "comparator", "baseline_tokens_per_sec")
    delta = _get(report, "comparator", "delta_pct")
    causes = _get(report, "comparator", "probable_causes", default=[]) or []

    def esc(value: Any) -> str:
        return html.escape(str(value)) if value is not None else "—"

    metric_rows = [
        ("Tokens / sec", _fmt(tps)),
        ("Baseline tokens / sec", _fmt(baseline)),
        ("Delta vs baseline", _fmt(delta, "%", 1)),
        ("p50 latency", _fmt(_get(report, "metrics", "latency", "p50_ms"), " ms")),
        ("p90 latency", _fmt(_get(report, "metrics", "latency", "p90_ms"), " ms")),
        ("p99 latency", _fmt(_get(report, "metrics", "latency", "p99_ms"), " ms")),
        ("Peak RAM", _fmt(_get(report, "metrics", "peak_ram_mb"), " MB", 0)),
        ("Peak VRAM", _fmt(_get(report, "metrics", "peak_vram_mb"), " MB", 0)),
        ("Avg power", _fmt(_get(report, "metrics", "avg_power_w"), " W", 1)),
        ("CPU utilization", _fmt(_get(report, "metrics", "cpu_util_pct"), "%", 1)),
        ("GPU utilization", _fmt(_get(report, "metrics", "gpu_util_pct"), "%", 1)),
    ]

    device_rows = [
        ("OS", esc(_get(report, "device", "os"))),
        ("CPU", esc(_get(report, "device", "cpu"))),
        ("Cores / Threads",
         f"{esc(_get(report, 'device', 'cpu_cores'))} / {esc(_get(report, 'device', 'cpu_threads'))}"),
        ("GPU", esc(_get(report, "device", "gpu") or "None")),
        ("RAM", _fmt(_get(report, "device", "ram_gb"), " GB", 1)),
        ("Power plan", esc(_get(report, "device", "power_plan"))),
    ]

    def table(rows: List[tuple]) -> str:
        return "\n".join(
            f"<tr><td>{html.escape(label)}</td><td>{value}</td></tr>"
            for label, value in rows
        )

    causes_html = ""
    if causes:
        items = "\n".join(f"<li>{html.escape(str(c))}</li>" for c in causes)
        causes_html = f"""
    <section class="card warn">
      <h2>Probable causes</h2>
      <ul>{items}</ul>
    </section>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ScoobyBench Report — {esc(model)}</title>
<style>
  body {{ font-family: system-ui, sans-serif; background: #0f172a; color: #e2e8f0;
         max-width: 860px; margin: 40px auto; padding: 0 20px; }}
  h1 {{ font-size: 1.6rem; }} h2 {{ font-size: 1.05rem; color: #94a3b8; margin: 0 0 12px; }}
  .head {{ display: flex; justify-content: space-between; align-items: center; }}
  .grade {{ font-size: 2.6rem; font-weight: 800; color: {grade_color};
            border: 3px solid {grade_color}; border-radius: 14px; padding: 8px 22px; }}
  .card {{ background: #1e293b; border-radius: 12px; padding: 18px 22px; margin: 18px 0; }}
  .card.warn {{ border-left: 4px solid #f59e0b; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td {{ padding: 7px 4px; border-bottom: 1px solid #334155; }}
  td:first-child {{ color: #94a3b8; width: 45%; }}
  .meta {{ color: #64748b; font-size: 0.85rem; }}
</style>
</head>
<body>
  <div class="head">
    <div>
      <h1>🐕 ScoobyBench — {esc(model)}</h1>
      <p class="meta">Run {esc(report.get("run_id"))} · {esc(report.get("timestamp"))}</p>
    </div>
    <div class="grade">{esc(grade)}</div>
  </div>
  <section class="card"><h2>Performance</h2><table>{table(metric_rows)}</table></section>
  <section class="card"><h2>Device</h2><table>{table(device_rows)}</table></section>{causes_html}
  <p class="meta">Baseline source: {esc(_get(report, "comparator", "baseline_source"))} ·
     Generated by ScoobyBench</p>
</body>
</html>"""


CSV_COLUMNS = [
    ("run_id", ("run_id",)),
    ("timestamp", ("timestamp",)),
    ("model", ("model", "name")),
    ("precision", ("model", "precision")),
    ("batch_size", ("model", "batch_size")),
    ("repeats", ("model", "repeats")),
    ("tokens_per_sec", ("metrics", "tokens_per_sec")),
    ("p50_ms", ("metrics", "latency", "p50_ms")),
    ("p90_ms", ("metrics", "latency", "p90_ms")),
    ("p99_ms", ("metrics", "latency", "p99_ms")),
    ("peak_ram_mb", ("metrics", "peak_ram_mb")),
    ("peak_vram_mb", ("metrics", "peak_vram_mb")),
    ("avg_power_w", ("metrics", "avg_power_w")),
    ("cpu_util_pct", ("metrics", "cpu_util_pct")),
    ("gpu_util_pct", ("metrics", "gpu_util_pct")),
    ("baseline_tokens_per_sec", ("comparator", "baseline_tokens_per_sec")),
    ("delta_pct", ("comparator", "delta_pct")),
    ("grade", ("comparator", "grade")),
    ("cpu", ("device", "cpu")),
    ("gpu", ("device", "gpu")),
    ("ram_gb", ("device", "ram_gb")),
    ("os", ("device", "os")),
]


def generate_csv(reports: List[Dict[str, Any]]) -> str:
    """Render one or more benchmark reports as CSV (one row per run)."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow([name for name, _ in CSV_COLUMNS])
    for report in reports:
        writer.writerow([_get(report, *path, default="") for _, path in CSV_COLUMNS])
    return buffer.getvalue()
